apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: graphqls.conductor.com
spec:
  group: conductor.com
  names:
    kind: GraphQLSubgraph
    plural: graphqls
    singular: graphql
    shortNames:
      - gql
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                version:
                  type: string
                schemaUrl:
                  type: string
                routingUrl:
                  type: string
